version: '3'
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3300:3306"
    volumes:
      - mysql-data2:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/coffee-oma/:delegated
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true
    depends_on:
      - database
volumes:
  mysql-data2:
    driver: local
