name: feature
description: new feature
title: "[feature]: "
labels: ["New feature"]
assignees:
  - tomoron
body:
  - type: markdown
    attributes:
      value: |
        新しい機能のを追加するためのissueを書いてください。React,Railsなど関係なくissueを追加してください。
  - type: dropdown
    id: download
    attributes:
      label: How did you download the software?
      options:
        - Homebrew
        - MacPorts
        - apt-get
        - Built from source
  validations:
    required: true
  - type: textarea
    id: feature
    attributes:
      label: 新機能
      description: 新機能の説明
      placeholder: 'new feature'
      value: '新機能の説明'
    validations:
      required: true
