name: Cypress

on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml


jobs:
  cypress:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: tomoron/coffee-oma-react
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v2.2.7
        with:
          start: yarn start:ci
          working-directory: frontend
          wait-on: 'http://localhost:3000'
          config: baseUrl=http://localhost:3000
          browser: chrome
          headless: true
          env: SKIP_PREFLIGHT_CHECK=true
