name: Cypress

on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml


jobs:
  cypress:
    runs-on: ubuntu-20.04
    env:
      ENV_FILE: ${{ secrets.FRONT_ENV_FILE}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: tomoron/coffee-oma-react
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Decode env file
        run: echo $ENV_FILE | base64 -d > .env
        working-directory: frontend
      - name: Cypress run
        uses: cypress-io/github-action@v2.11.7
        with:
          start: yarn start:ci
          working-directory: frontend
          wait-on: 'http://localhost:3000'
          config: baseUrl=http://localhost:3000
          browser: chrome
          headless: true
