name: Cypress

on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml


jobs:
  cypress:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@2
        with:
          repository: tomoron/coffee-oma-react
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          working-directory: ./backend
