name: Rails Rspec
on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose,yml

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_POET: 3300
    services:
      database:
        image: mysql:8.0
        ports:
          - 3300:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: password
          BIND_ADDRESS: 0.0.0.0
        options:  --health-cmd "mysqladmin ping -h 127.0.0.1" --health-interval 20s --health-timeout 10s --health-retries 10
    steps:
      - uses: actions/checkout@v2
        with:
          repository: tomoron/coffee-oma-react
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: SET up Ruby 2.7.2
        uses: ruby/setup-ruby@v1.68.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: ./backend
      - name: LS
        run: ls
        working-directory: ./backend



