name: Rails Rspec
on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose,yml

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_POET: 3300
    services:
      database:
        image: mysql:8.0
        ports:
          - 3300:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yas
          BIND_ADDRESS: 0.0.0.0
    steps:
      - uses: actions/checkout@v2
        with:
          repository: tomoron/coffee-oma-react
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: SET up Ruby 2.7.2
        uses: ruby/setup-ruby@v1.68.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: cd backend
        run: cd backend
      - name: bundle install
        run: bundle install --jobs=4
      - name: migration
        run: |
          bundle exec rails db:create
          bundle exec rails db:test:prepare
      - name: run rubocop
        run: rubocop
      - name: run rspec
        run: bundle exec rspec

